language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - TEST_COMMAND=test FEATURES=''

matrix:
  include:
    - rust: nightly
      env: TEST_COMMAND=build FEATURES=--no-default-features
    - rust: nightly
      env: TEST_COMMAND=test FEATURES=--features="nightly"
    - rust: nightly
      env: TEST_COMMAND=bench FEATURES=--features="bench"
    - rust: nightly
      env: TEST_COMMAND=bench FEATURES=--features="nightly bench"

script:
  - cargo $TEST_COMMAND $FEATURES
